### ISSUE TITLE
bubble sort swapping function

### ISSUE THREAD

**Issue by jjmax75** [dereklawless/algorithms-and-data-structures-katas#1]
a nice way to swap elements of an array in es6 (no need for a temp var)

`const swap = (i, j) => ([arr[i], arr[j]] = [arr[j], arr[i]]);`

**Comment by dereklawless** [comment]
Thanks John. In the interests of keeping things simple ™️  I'm not going to add this.

**Comment by jjmax75** [comment]
I think that's reasonable, the destructuring approach always felt unintuitive to me
